#!/usr/bin/env python
"""Write a .env for docker compose with fresh random secrets.

    python scripts/make_env.py            create .env (refuses to overwrite)
    python scripts/make_env.py --demo     also create demo logins dr.rao / auditor with random passwords
    python scripts/make_env.py --force    replace an existing .env (existing data volumes will no longer open!)

Nothing here is a default password: every secret is generated on this machine and printed once.
"""
import argparse
import secrets
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--demo", action="store_true", help="add clinician and auditor logins")
    ap.add_argument("--force", action="store_true")
    ap.add_argument("--out", default=str(ROOT / ".env"))
    a = ap.parse_args()
    out = Path(a.out)
    if out.exists() and not a.force:
        sys.exit(f"{out} already exists. Keep it (its keys open your existing data) or pass --force.")
    pw = lambda: secrets.token_urlsafe(14)  # noqa: E731
    v = {
        "QKD_AUTH_KEY": secrets.token_hex(32),
        "QKD_MASTER_KEY_A": secrets.token_hex(32),
        "QKD_MASTER_KEY_B": secrets.token_hex(32),
        "ADMIN_PASSWORD_A": pw(),
        "ADMIN_PASSWORD_B": pw(),
        "KME_API_KEY_A": secrets.token_urlsafe(24),
        "KME_API_KEY_B": secrets.token_urlsafe(24),
    }
    if a.demo:
        v.update({"DEMO_USERS": "1", "CLINICIAN_PASSWORD": pw(), "AUDITOR_PASSWORD": pw()})
    out.write_text("# Generated by scripts/make_env.py. Keep this file private: it holds the keys that\n"
                   "# encrypt each hospital's database. Losing QKD_MASTER_KEY_* makes that data unreadable.\n"
                   + "".join(f"{k}={x}\n" for k, x in v.items()))
    try:
        out.chmod(0o600)
    except OSError:
        pass
    print(f"Wrote {out}\n")
    print("Sign in to both hospitals with:")
    print(f"  admin / Hospital A: {v['ADMIN_PASSWORD_A']}")
    print(f"  admin / Hospital B: {v['ADMIN_PASSWORD_B']}")
    if a.demo:
        print(f"  dr.rao / {v['CLINICIAN_PASSWORD']}      auditor / {v['AUDITOR_PASSWORD']}")
    else:
        print("\nThen, as admin, add a clinician under Users. (Or rerun with --demo for ready-made demo logins.)")
    print("\nStart it:  docker compose up --build")


if __name__ == "__main__":
    main()
